--- #YAML:1.0
name:                ExtUtils-Install
version:             1.51
abstract:            install files from here to there
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Carp:                          0
    Cwd:                           0
    ExtUtils::MakeMaker:           0
    File::Basename:                0
    File::Compare:                 0
    File::Copy:                    0
    File::Find:                    0
    File::Path:                    0
    File::Spec:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - demerphq <yves@cpan.org>
