---
name: ExtUtils-Install
version: 1.49
author:
  - 'demerphq <yves@cpan.org>'
abstract: install files from here to there
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Cwd: 0
  ExtUtils::MakeMaker: 0
  File::Basename: 0
  File::Compare: 0
  File::Copy: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  perl: 5.006
dynamic_config: 1
provides:
  ExtUtils::Install:
    file: lib/ExtUtils/Install.pm
    version: 1.49
  ExtUtils::Install::Warn:
    file: lib/ExtUtils/Install.pm
  ExtUtils::Installed:
    file: lib/ExtUtils/Installed.pm
    version: 1.43
  ExtUtils::Packlist:
    file: lib/ExtUtils/Packlist.pm
    version: 1.43
generated_by: Module::Build version 0.280802
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
